name: Alert

on:

  workflow_dispatch:
concurrency:
  group: discord-bot
  cancel-in-progress: false
jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:
          node-version: 22

      - run: npm install

      - run: node main.js alert

        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TASK_DATABASE_ID: ${{ secrets.TASK_DATABASE_ID }}
          NOTIFICATION_DATABASE_ID: ${{ secrets.NOTIFICATION_DATABASE_ID }}
          USER_DATABASE_ID: ${{ secrets.USER_DATABASE_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
